openapi: 3.0.3
info:
    title: Game Service
    description: Service for a multiplayer game
    version: "1.0"
servers:
    - url: http://localhost:8000
paths:
    /back/characters:
        get:
            tags:
                - character
            summary: list character
            description: List all characters
            operationId: character#list
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoredCharacterResponseCollection'
                            example:
                                - description: A grizzled wizard with a penchant for mayhem and mead
                                  experience: 47735
                                  health: 495
                                  id: 123abc
                                  name: Arvish the Wise
                                - description: A grizzled wizard with a penchant for mayhem and mead
                                  experience: 47735
                                  health: 495
                                  id: 123abc
                                  name: Arvish the Wise
                                - description: A grizzled wizard with a penchant for mayhem and mead
                                  experience: 47735
                                  health: 495
                                  id: 123abc
                                  name: Arvish the Wise
                                - description: A grizzled wizard with a penchant for mayhem and mead
                                  experience: 47735
                                  health: 495
                                  id: 123abc
                                  name: Arvish the Wise
        post:
            tags:
                - character
            summary: add character
            description: Add new character and return its ID
            operationId: character#add
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddRequestBody2'
                        example:
                            description: A grizzled wizard with a penchant for mayhem and mead
                            experience: 83494
                            health: 157
                            name: Arvish the Wise
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Enim cumque autem.
                            example: Fuga quis aut et et pariatur eos.
                "409":
                    description: 'name_taken: name is taken'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NameTaken'
                            example:
                                message: Ea totam at.
                                name: Aut sunt ratione illo.
    /back/characters/{id}:
        delete:
            tags:
                - character
            summary: remove character
            description: Remove a character
            operationId: character#remove
            parameters:
                - name: id
                  in: path
                  description: ID of character to remove
                  required: true
                  schema:
                    type: string
                    description: ID of character to remove
                    example: Amet ut.
                  example: Sed cumque sapiente sapiente.
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'not_found: character not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFound'
                            example:
                                id: Mollitia ut harum autem ipsam ratione atque.
                                message: In quia eos voluptas et non velit.
        get:
            tags:
                - character
            summary: show character
            description: Show character by ID
            operationId: character#show
            parameters:
                - name: view
                  in: query
                  description: View to render
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: View to render
                    example: tiny
                    enum:
                        - default
                        - tiny
                  example: default
                - name: id
                  in: path
                  description: ID of character to show
                  required: true
                  schema:
                    type: string
                    description: ID of character to show
                    example: Ipsa vitae molestias itaque animi.
                  example: Qui consequatur ut nisi expedita et.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoredCharacter'
                            example:
                                description: A grizzled wizard with a penchant for mayhem and mead
                                experience: 82605
                                health: 384
                                id: 123abc
                                name: Arvish the Wise
                "404":
                    description: 'not_found: character not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFound'
                            example:
                                id: Dolorum officia modi harum nulla.
                                message: Quaerat atque enim molestias modi harum.
        put:
            tags:
                - character
            summary: update character
            description: Update a character with the given ID
            operationId: character#update
            parameters:
                - name: id
                  in: path
                  description: ID of the character to be updated
                  required: true
                  schema:
                    type: string
                    description: ID of the character to be updated
                    example: Vitae quae dolores.
                  example: Quia sint qui dolorem.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody2'
                        example:
                            character:
                                description: A grizzled wizard with a penchant for mayhem and mead
                                experience: 44185
                                health: 1543
                                name: Arvish the Wise
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'not_found: character not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFound'
                            example:
                                id: Aperiam nihil.
                                message: Accusamus consequatur voluptatum officia.
                "409":
                    description: 'name_taken: name is taken'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NameTaken'
                            example:
                                message: Minus voluptatem voluptas quam.
                                name: Qui maiores vitae odit rerum provident.
    /back/items:
        get:
            tags:
                - item
            summary: list item
            description: List all items
            operationId: item#list
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoredItemResponseCollection'
                            example:
                                - damage: 123
                                  description: A magnificent sword which grants the bearer +2 wisdom
                                  healing: 17
                                  id: 123abc
                                  name: Sword of Wisdom
                                  protection: 18
                                - damage: 123
                                  description: A magnificent sword which grants the bearer +2 wisdom
                                  healing: 17
                                  id: 123abc
                                  name: Sword of Wisdom
                                  protection: 18
                                - damage: 123
                                  description: A magnificent sword which grants the bearer +2 wisdom
                                  healing: 17
                                  id: 123abc
                                  name: Sword of Wisdom
                                  protection: 18
                                - damage: 123
                                  description: A magnificent sword which grants the bearer +2 wisdom
                                  healing: 17
                                  id: 123abc
                                  name: Sword of Wisdom
                                  protection: 18
        post:
            tags:
                - item
            summary: add item
            description: Add new item and return its ID
            operationId: item#add
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddRequestBody'
                        example:
                            damage: 2
                            description: A magnificent sword which grants the bearer +2 wisdom
                            healing: 75
                            name: Sword of Wisdom
                            protection: 10
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Aut optio quo temporibus repudiandae.
                            example: Doloremque fugiat impedit sed cum sapiente voluptate.
                "409":
                    description: 'name_taken: name is taken'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NameTaken'
                            example:
                                message: Ipsum error alias velit veritatis.
                                name: Ratione omnis doloribus autem at.
    /back/items/{id}:
        delete:
            tags:
                - item
            summary: remove item
            description: Remove an item
            operationId: item#remove
            parameters:
                - name: id
                  in: path
                  description: ID of item to remove
                  required: true
                  schema:
                    type: string
                    description: ID of item to remove
                    example: Dolorem quo et.
                  example: Totam rem exercitationem praesentium.
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'not_found: Item not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFound'
                            example:
                                id: Dignissimos voluptatem ipsam quos id saepe.
                                message: Officia nisi minima tempora deleniti.
        get:
            tags:
                - item
            summary: show item
            description: Show item by ID
            operationId: item#show
            parameters:
                - name: view
                  in: query
                  description: View to render
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: View to render
                    example: tiny
                    enum:
                        - default
                        - tiny
                  example: tiny
                - name: id
                  in: path
                  description: ID of item to show
                  required: true
                  schema:
                    type: string
                    description: ID of item to show
                    example: Eum enim.
                  example: Esse ducimus voluptatem qui enim modi.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoredItem'
                            example:
                                damage: 54
                                description: A magnificent sword which grants the bearer +2 wisdom
                                healing: 164
                                id: 123abc
                                name: Sword of Wisdom
                                protection: 11
                "404":
                    description: 'not_found: Item not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFound'
                            example:
                                id: Voluptatem officia quis.
                                message: Vel placeat atque.
        put:
            tags:
                - item
            summary: update item
            description: Update an item with the given ID
            operationId: item#update
            parameters:
                - name: id
                  in: path
                  description: ID of the item to be updated
                  required: true
                  schema:
                    type: string
                    description: ID of the item to be updated
                    example: Culpa voluptas vel non voluptas blanditiis.
                  example: Maiores voluptatem natus est occaecati sapiente.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody'
                        example:
                            item:
                                damage: 49
                                description: A magnificent sword which grants the bearer +2 wisdom
                                healing: 103
                                name: Sword of Wisdom
                                protection: 12
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'not_found: Item not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFound'
                            example:
                                id: Ut expedita nisi cumque voluptas soluta rerum.
                                message: Quo magni.
                "409":
                    description: 'name_taken: name is taken'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NameTaken'
                            example:
                                message: Nam in repellendus architecto non quia.
                                name: Qui deleniti dolore.
    /items:
        get:
            tags:
                - front
            summary: list-items front
            description: List all items
            operationId: front#list-items
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoredItemCollection'
                            example:
                                - damage: 191
                                  description: A magnificent sword which grants the bearer +2 wisdom
                                  healing: 141
                                  id: 123abc
                                  name: Sword of Wisdom
                                  protection: 9
                                - damage: 191
                                  description: A magnificent sword which grants the bearer +2 wisdom
                                  healing: 141
                                  id: 123abc
                                  name: Sword of Wisdom
                                  protection: 9
components:
    schemas:
        AddRequestBody:
            type: object
            properties:
                damage:
                    type: integer
                    description: Amount of damage the item can do
                    example: 147
                    minimum: 0
                    maximum: 200
                description:
                    type: string
                    description: Description of item
                    example: A magnificent sword which grants the bearer +2 wisdom
                    maxLength: 2000
                healing:
                    type: integer
                    description: Amount of healing the item can provide
                    example: 169
                    minimum: 0
                    maximum: 200
                name:
                    type: string
                    description: Name of item
                    example: Sword of Wisdom
                    maxLength: 100
                protection:
                    type: integer
                    description: Amount of protection the item can provide
                    example: 6
                    minimum: 0
                    maximum: 20
            example:
                damage: 133
                description: A magnificent sword which grants the bearer +2 wisdom
                healing: 115
                name: Sword of Wisdom
                protection: 1
            required:
                - name
                - damage
                - healing
                - protection
        AddRequestBody2:
            type: object
            properties:
                description:
                    type: string
                    description: Description of the character
                    example: A grizzled wizard with a penchant for mayhem and mead
                    maxLength: 2000
                experience:
                    type: integer
                    description: Amount of experience the character has
                    example: 19105
                    minimum: 0
                    maximum: 100000
                health:
                    type: integer
                    description: Amount of health the character has
                    example: 1329
                    minimum: 0
                    maximum: 2000
                name:
                    type: string
                    description: Name of the character
                    example: Arvish the Wise
                    maxLength: 100
            example:
                description: A grizzled wizard with a penchant for mayhem and mead
                experience: 68276
                health: 360
                name: Arvish the Wise
            required:
                - name
                - health
        NameTaken:
            type: object
            properties:
                message:
                    type: string
                    description: name taken
                    example: Vel et earum vero.
                name:
                    type: string
                    description: name that is not unique
                    example: Ad repudiandae et.
            description: name is taken
            example:
                message: Voluptas ut libero delectus.
                name: Velit aut velit.
            required:
                - message
                - name
        NotFound:
            type: object
            properties:
                id:
                    type: string
                    description: ID of missing item
                    example: Optio illo excepturi.
                message:
                    type: string
                    description: not found
                    example: Consequatur at.
            description: Item not found
            example:
                id: Laboriosam et.
                message: Nihil aliquam.
            required:
                - message
                - id
        StoredCharacter:
            type: object
            properties:
                description:
                    type: string
                    description: Description of the character
                    example: A grizzled wizard with a penchant for mayhem and mead
                    maxLength: 2000
                experience:
                    type: integer
                    description: Amount of experience the character has
                    example: 76940
                    minimum: 0
                    maximum: 100000
                health:
                    type: integer
                    description: Amount of health the character has
                    example: 1883
                    minimum: 0
                    maximum: 2000
                id:
                    type: string
                    description: ID is the unique id of the character.
                    example: 123abc
                name:
                    type: string
                    description: Name of the character
                    example: Arvish the Wise
                    maxLength: 100
            example:
                description: A grizzled wizard with a penchant for mayhem and mead
                experience: 6527
                health: 119
                id: 123abc
                name: Arvish the Wise
            required:
                - id
                - name
                - health
                - experience
        StoredCharacterResponse:
            type: object
            properties:
                description:
                    type: string
                    description: Description of the character
                    example: A grizzled wizard with a penchant for mayhem and mead
                    maxLength: 2000
                experience:
                    type: integer
                    description: Amount of experience the character has
                    example: 6796
                    minimum: 0
                    maximum: 100000
                health:
                    type: integer
                    description: Amount of health the character has
                    example: 198
                    minimum: 0
                    maximum: 2000
                id:
                    type: string
                    description: ID is the unique id of the character.
                    example: 123abc
                name:
                    type: string
                    description: Name of the character
                    example: Arvish the Wise
                    maxLength: 100
            description: A StoredCharacter describes an character stored with an ID (default view)
            example:
                description: A grizzled wizard with a penchant for mayhem and mead
                experience: 23394
                health: 1975
                id: 123abc
                name: Arvish the Wise
            required:
                - id
                - name
                - health
                - experience
        StoredCharacterResponseCollection:
            type: array
            items:
                $ref: '#/components/schemas/StoredCharacterResponse'
            description: ListResponseBody is the result type for an array of StoredCharacterResponse (default view)
            example:
                - description: A grizzled wizard with a penchant for mayhem and mead
                  experience: 47735
                  health: 495
                  id: 123abc
                  name: Arvish the Wise
                - description: A grizzled wizard with a penchant for mayhem and mead
                  experience: 47735
                  health: 495
                  id: 123abc
                  name: Arvish the Wise
                - description: A grizzled wizard with a penchant for mayhem and mead
                  experience: 47735
                  health: 495
                  id: 123abc
                  name: Arvish the Wise
        StoredItem:
            type: object
            properties:
                damage:
                    type: integer
                    description: Amount of damage the item can do
                    example: 158
                    minimum: 0
                    maximum: 200
                description:
                    type: string
                    description: Description of item
                    example: A magnificent sword which grants the bearer +2 wisdom
                    maxLength: 2000
                healing:
                    type: integer
                    description: Amount of healing the item can provide
                    example: 9
                    minimum: 0
                    maximum: 200
                id:
                    type: string
                    description: ID is the unique id of the item.
                    example: 123abc
                name:
                    type: string
                    description: Name of item
                    example: Sword of Wisdom
                    maxLength: 100
                protection:
                    type: integer
                    description: Amount of protection the item can provide
                    example: 15
                    minimum: 0
                    maximum: 20
            example:
                damage: 152
                description: A magnificent sword which grants the bearer +2 wisdom
                healing: 102
                id: 123abc
                name: Sword of Wisdom
                protection: 1
            required:
                - id
                - name
                - damage
                - healing
                - protection
        StoredItemCollection:
            type: array
            items:
                $ref: '#/components/schemas/StoredItem'
            example:
                - damage: 191
                  description: A magnificent sword which grants the bearer +2 wisdom
                  healing: 141
                  id: 123abc
                  name: Sword of Wisdom
                  protection: 9
                - damage: 191
                  description: A magnificent sword which grants the bearer +2 wisdom
                  healing: 141
                  id: 123abc
                  name: Sword of Wisdom
                  protection: 9
                - damage: 191
                  description: A magnificent sword which grants the bearer +2 wisdom
                  healing: 141
                  id: 123abc
                  name: Sword of Wisdom
                  protection: 9
                - damage: 191
                  description: A magnificent sword which grants the bearer +2 wisdom
                  healing: 141
                  id: 123abc
                  name: Sword of Wisdom
                  protection: 9
        StoredItemResponse:
            type: object
            properties:
                damage:
                    type: integer
                    description: Amount of damage the item can do
                    example: 197
                    minimum: 0
                    maximum: 200
                description:
                    type: string
                    description: Description of item
                    example: A magnificent sword which grants the bearer +2 wisdom
                    maxLength: 2000
                healing:
                    type: integer
                    description: Amount of healing the item can provide
                    example: 57
                    minimum: 0
                    maximum: 200
                id:
                    type: string
                    description: ID is the unique id of the item.
                    example: 123abc
                name:
                    type: string
                    description: Name of item
                    example: Sword of Wisdom
                    maxLength: 100
                protection:
                    type: integer
                    description: Amount of protection the item can provide
                    example: 8
                    minimum: 0
                    maximum: 20
            description: A StoredItem describes an item stored with an ID (default view)
            example:
                damage: 35
                description: A magnificent sword which grants the bearer +2 wisdom
                healing: 195
                id: 123abc
                name: Sword of Wisdom
                protection: 19
            required:
                - id
                - name
                - damage
                - healing
                - protection
        StoredItemResponseCollection:
            type: array
            items:
                $ref: '#/components/schemas/StoredItemResponse'
            description: ListResponseBody is the result type for an array of StoredItemResponse (default view)
            example:
                - damage: 123
                  description: A magnificent sword which grants the bearer +2 wisdom
                  healing: 17
                  id: 123abc
                  name: Sword of Wisdom
                  protection: 18
                - damage: 123
                  description: A magnificent sword which grants the bearer +2 wisdom
                  healing: 17
                  id: 123abc
                  name: Sword of Wisdom
                  protection: 18
                - damage: 123
                  description: A magnificent sword which grants the bearer +2 wisdom
                  healing: 17
                  id: 123abc
                  name: Sword of Wisdom
                  protection: 18
        UpdateRequestBody:
            type: object
            properties:
                item:
                    $ref: '#/components/schemas/AddRequestBody'
            example:
                item:
                    damage: 49
                    description: A magnificent sword which grants the bearer +2 wisdom
                    healing: 103
                    name: Sword of Wisdom
                    protection: 12
            required:
                - item
        UpdateRequestBody2:
            type: object
            properties:
                character:
                    $ref: '#/components/schemas/AddRequestBody2'
            example:
                character:
                    description: A grizzled wizard with a penchant for mayhem and mead
                    experience: 44185
                    health: 1543
                    name: Arvish the Wise
            required:
                - character
tags:
    - name: item
      description: The item service is the service for managing items
    - name: character
      description: The character service is the service for managing characters
    - name: front
      description: The front service is the main HTTP API for the game
